### ISSUE TITLE
Parameter not defined in inflate.py

### ISSUE THREAD

**Issue by rmaria** [hassony2/inflated_convnets_pytorch#6]
Hi Yana,
Thank you for sharing this code. 
In inflate.py you call two times Parameter(weights_3d), but Parameter() is not imported or defined in the code. Could you please share this function?
Thank you,
Robert

**Comment by hassony2** [comment]
Hi @rmaria,

Thank you for pointing this out !
I added the missing import of [Parameter](https://pytorch.org/docs/stable/nn.html#torch.nn.Parameter) from PyTorch: https://github.com/hassony2/inflated_convnets_pytorch/commit/c8ce4c684f76c128703808390cdd66c3a074afc4

Hope this helps !

Best,

Yana
